export const GET_ERRORS_LOGIN = 'GET_ERRORS_LOGIN';
export const GET_ERRORS_REGISTER = 'GET_ERRORS_REGISTER';
export const GET_ERRORS_INPUTPRODUCT = 'GET_ERRORS_INPUTPRODUCT';
export const GET_ERRORS_SELLPRODUCT = 'GET_ERRORS_SELLPRODUCT';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
